### ISSUE TITLE
'Older' link leads to 404

### ISSUE THREAD

**Issue by achudzik** [marcingrzejszczak/marcingrzejszczak.github.io#1]
Clicking the 'Older' button on the main page redirects to http://toomuchcoding.com/_posts/2 which is a 404 page.

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/marcingrzejszczak/marcingrzejszczak.github.io/commit/48f791fb3b08705fcb3d28afdc0936820230f475
